name: Setup Terminus
description: "Install and configure the Pantheon CLI tool, Terminus."
branding:
  icon: "cloud"
  color: "yellow"
inputs:
  pantheon-machine-token:
    description: "Machine token used to authenticate with Pantheon."
    required: false
  terminus-version:
    description: |
      The full version of Terminus to install. If omitted, the latest version is used.
    required: false
  disable-cache:
    description: Disable session cache and force a new session to be initiated.
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Set Terminus version
      if: ${{ ! inputs.terminus-version }}
      shell: bash
      run: |
        TERMINUS_RELEASE=$(
          curl --silent \
            --header 'authorization: Bearer ${{ github.token }}' \
            "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" \
            | perl -nle'print $& while m#"tag_name": "\K[^"]*#g'
        )
        echo "TERMINUS_RELEASE=$TERMINUS_RELEASE" >> $GITHUB_ENV

    - name: Install Terminus
      shell: bash
      run: |
        mkdir $HOME/terminus && cd $HOME/terminus
        echo "Installing Terminus v$TERMINUS_RELEASE"
        curl -L https://github.com/pantheon-systems/terminus/releases/download/$TERMINUS_RELEASE/terminus.phar --output terminus
        chmod +x terminus
        sudo ln -s $HOME/terminus/terminus /usr/local/bin/terminus
        mkdir -p $HOME/.terminus/{cache,plugins}
      env:
        TERMINUS_RELEASE: ${{ inputs.terminus-version || env.TERMINUS_RELEASE }}

    - name: Cache Terminus plugin directory
      uses: actions/cache@v4
      id: terminus-plugin-cache
      with:
        path: $HOME/.terminus/plugins
        key: ${{ runner.os }}-terminus-plugins
        restore-keys: |
          ${{ runner.os }}-terminus-plugins-

    - name: Set a cache path, key, and restore-key
      id: configure-cache
      shell: bash
      run: |

        # Set cache path, key, and restore-key.
        echo "path=${{ runner.temp }}/terminus-session.gpg" >> $GITHUB_OUTPUT

        machine_token_hash=`echo ${{ inputs.pantheon-machine-token }} | sha256sum | head -c 40`
        restore_key="terminus-session-$machine_token_hash"
        echo "restore-key=$restore_key-" >> $GITHUB_OUTPUT

        # Use the GitHub Actions "run id" to uniqify the cache key so that we
        # can force initiating a new session when requested via action input
        # (GitHub Actions caches are immutable and can't be updated for a given
        # key).
        # @see https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        echo "key=$restore_key-${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Restore cached encrypted Terminus session
      id: restore-cache
      if: ${{ inputs.disable-cache != 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache.outputs.path }}
        key: ${{ steps.cache.outputs.key }}
        restore-keys: ${{ steps.cache.outputs.restore-key }}
        enableCrossOsArchive: true

    - name: Decrypt cached session file
      id: decrypt
      if: ${{ steps.restore-cache.outcome == 'success' }}
      continue-on-error: true
      shell: bash
      run: |

        # Verify that the encrypted session file was restored from cache.
        test -s ${{ steps.cache.outputs.path }}

        # Decrypt the session file using the "file descriptor" passphrase option
        # (--passphrase-fd) instead of regular --passphrase because it's more
        # secure to pipe the secret than to pass it as a command argument.
        echo ${{ inputs.pantheon-machine-token }} | \
          gpg2 --passphrase-fd \
               --batch \
               --yes \
               --pinentry loopback \
               --output terminus-session-temp \
               --decrypt ${{ steps.cache.outputs.path }}

        # Move the session file into the Terminus cache directory.
        mv terminus-session-temp $TERMINUS_CACHE_DIR/session

        # Check if restored session is still valid
        terminus auth:whoami

    - name: Authenticate Terminus
      id: authenticate
      if: ${{ inputs.pantheon-machine-token }}
      continue-on-error: true
      shell: bash
      run: |
        terminus auth:login || terminus auth:login --machine-token="${{ inputs.pantheon-machine-token }}"

    - name: Encrypt new Terminus session (if needed)
      id: encrypt-cache
      if: ${{ steps.decrypt.outcome != 'success' && steps.authenticate.outcome == 'success'}}
      shell: bash
      run: |

        # Copy the session file to a mounted folder
        cp $TERMINUS_CACHE_DIR/session terminus-session-temp

        # Encrypt the session file using the "file descriptor" passphrase option
        # (--passphrase-fd) instead of regular --passphrase because it's more
        # secure to pipe the secret than pass it as a command argument.

        echo ${{ inputs.pantheon-machine-token }} | \
          gpg2 --passphrase-fd \
               --batch \
               --yes \
               --pinentry-mode loopback \
               --output ${{ steps.cache.outputs.path }} \
               --symmetric terminus-session-temp

        # Remove the temporary session file we copied.
        rm terminus-session-temp

    - name: Cache encrypted Terminus session
      id: save-cache
      if: ${{ steps.encrypt.outcome == 'success' }}
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.cache.outputs.path }}
        key: ${{ steps.cache.outputs.key }}
        enableCrossOsArchive: true
