name: Setup Terminus
description: "Install and configure the Pantheon CLI tool, Terminus."
branding:
  icon: "cloud"
  color: "yellow"
inputs:
  pantheon-machine-token:
    description: "Machine token used to authenticate with Pantheon."
    required: false
  terminus-version:
    description: |
      The full version of Terminus to install. If omitted, the latest version is used.
    required: false
runs:
  using: composite
  steps:
    - name: Determine version
      shell: bash
      if: ${{ ! inputs.terminus-version }}
      run: |
        TERMINUS_RELEASE=$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m#"tag_name": "\K[^"]*#g')
        echo "TERMINUS_RELEASE=$TERMINUS_RELEASE" >> $GITHUB_ENV

    - name: Install Terminus
      shell: bash
      run: |
        mkdir ~/terminus && cd ~/terminus
        echo "Installing Terminus v$TERMINUS_RELEASE"
        curl -L https://github.com/pantheon-systems/terminus/releases/download/$TERMINUS_RELEASE/terminus.phar --output terminus
        chmod +x terminus
        sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
      env:
        TERMINUS_RELEASE: ${{ inputs.terminus-version || env.TERMINUS_RELEASE }}

    - name: Login to Pantheon
      if: ${{ inputs.pantheon-machine-token }}
      shell: bash
      run: |
        terminus auth:login --machine-token="${{ inputs.pantheon-machine-token }}"
