name: Setup Terminus
description: "Install and configure the Pantheon CLI tool, Terminus."
branding:
  icon: "cloud"
  color: "yellow"
inputs:
  pantheon-machine-token:
    description: "Machine token used to authenticate with Pantheon."
    required: true
  terminus-version:
    description: |
      The full version of Terminus to install. If omitted, the latest version is used.
    required: false
  build-tools-plugin:
    description: |
      The major version of `terminus-build-tools-plugin` to install, if any.

      Should be `v3` for Terminus v3, and `v2` for Terminus v2 - any other values are ignored
    required: false
runs:
  using: composite
  steps:
    - name: Determine version
      shell: bash
      if: ${{ ! inputs.terminus-version }}
      run: |
        TERMINUS_RELEASE=$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m#"tag_name": "\K[^"]*#g')
        echo "TERMINUS_RELEASE=$TERMINUS_RELEASE" >> $GITHUB_ENV

    - name: Install Terminus
      shell: bash
      run: |
        mkdir ~/terminus && cd ~/terminus
        echo "Installing Terminus v$TERMINUS_RELEASE"
        curl -L https://github.com/pantheon-systems/terminus/releases/download/$TERMINUS_RELEASE/terminus.phar --output terminus
        chmod +x terminus
        sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
      env:
        TERMINUS_RELEASE: ${{ inputs.terminus-version || env.TERMINUS_RELEASE }}

    - name: Install Terminus Build Tools v3
      shell: bash
      if: ${{ inputs.build-tools-plugin == 'v3' }}
      run: |
        terminus self:plugin:install terminus-build-tools-plugin

    - name: Install Terminus Build Tools v2
      shell: bash
      if: ${{ inputs.build-tools-plugin == 'v2' }}
      run: |
        mkdir -p ~/.terminus/plugins
        composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^2

    - name: Login to Pantheon
      shell: bash
      run: |
        terminus auth:login --machine-token="${{ inputs.pantheon-machine-token }}"
